# Generated by Django 4.2.4 on 2023-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='testnull@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
